// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFCkVU1uyK7khBLHx3GLn_y_pgkp9qFAA',
    appId: '1:96091168311:web:8881ac6eb115c57c52a9b2',
    messagingSenderId: '96091168311',
    projectId: 'futterdemo-84bd3',
    authDomain: 'futterdemo-84bd3.firebaseapp.com',
    databaseURL: 'https://futterdemo-84bd3-default-rtdb.firebaseio.com',
    storageBucket: 'futterdemo-84bd3.firebasestorage.app',
    measurementId: 'G-CMLZ79LV60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfRWAghH1KmNxxBVrL_Mw2qXNtHEDZmPU',
    appId: '1:96091168311:android:1a2a3a46163a678452a9b2',
    messagingSenderId: '96091168311',
    projectId: 'futterdemo-84bd3',
    databaseURL: 'https://futterdemo-84bd3-default-rtdb.firebaseio.com',
    storageBucket: 'futterdemo-84bd3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6kI5b-mkJArOg1RxllYGcXx2WZDDmsys',
    appId: '1:96091168311:ios:c77db5c9046f2c7552a9b2',
    messagingSenderId: '96091168311',
    projectId: 'futterdemo-84bd3',
    databaseURL: 'https://futterdemo-84bd3-default-rtdb.firebaseio.com',
    storageBucket: 'futterdemo-84bd3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6kI5b-mkJArOg1RxllYGcXx2WZDDmsys',
    appId: '1:96091168311:ios:c77db5c9046f2c7552a9b2',
    messagingSenderId: '96091168311',
    projectId: 'futterdemo-84bd3',
    databaseURL: 'https://futterdemo-84bd3-default-rtdb.firebaseio.com',
    storageBucket: 'futterdemo-84bd3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFCkVU1uyK7khBLHx3GLn_y_pgkp9qFAA',
    appId: '1:96091168311:web:2c0539f9fef02ee752a9b2',
    messagingSenderId: '96091168311',
    projectId: 'futterdemo-84bd3',
    authDomain: 'futterdemo-84bd3.firebaseapp.com',
    databaseURL: 'https://futterdemo-84bd3-default-rtdb.firebaseio.com',
    storageBucket: 'futterdemo-84bd3.firebasestorage.app',
    measurementId: 'G-NQCK4W57QF',
  );
}
